# -*- coding: utf-8 -*-
"""
error_analysis_baseline.py

Sentence-level error analysis for Dictionary and TF-IDF baseline models.
Produces reports in the same format as error_analysis_BERT_sentence.py.

Input CSVs are the sentence-level prediction files generated by each baseline:
  dictionary_baseline/sentence/test_predictions.csv
  dictionary_baseline/sentence/generalization_test_predictions.csv
  tfidf_baseline/test_predictions.csv
  tfidf_baseline/generalization_test_predictions.csv

Output:
  error_analysis/dict_sentence_test_report.txt
  error_analysis/dict_sentence_generalization_report.txt
  error_analysis/tfidf_sentence_test_report.txt
  error_analysis/tfidf_sentence_generalization_report.txt

Usage:
    python error_analysis_baseline.py
    python error_analysis_baseline.py --examples 5
"""

import argparse

from error_analysis_BERT_sentence import run_single

DEFAULT_RUNS = [
    (
        "dictionary_baseline/sentence/test_predictions.csv",
        "error_analysis/dict_sentence_test_report.txt",
    ),
    (
        "dictionary_baseline/sentence/generalization_test_predictions.csv",
        "error_analysis/dict_sentence_generalization_report.txt",
    ),
    (
        "tfidf_baseline/test_predictions.csv",
        "error_analysis/tfidf_sentence_test_report.txt",
    ),
    (
        "tfidf_baseline/generalization_test_predictions.csv",
        "error_analysis/tfidf_sentence_generalization_report.txt",
    ),
]


def main():
    parser = argparse.ArgumentParser(
        description="Sentence-level error analysis for Dictionary and TF-IDF baselines"
    )
    parser.add_argument(
        "--examples",
        type=int,
        default=10,
        help="Max examples shown per bucket (default: 10)",
    )
    args = parser.parse_args()

    for csv_path, out_path in DEFAULT_RUNS:
        run_single(csv_path, out_path, n_examples=args.examples)


if __name__ == "__main__":
    main()
